export const SLASH_COMMANDS = [
  // ─── BUILD: FULL APPS ───────────────────────────────────────────────────────
  { command: "/build-nodejs-app", description: "Scaffold a complete Node.js + Express Twilio app with package.json, .env, and all routes." },
  { command: "/build-nextjs-app", description: "Build a full-stack Next.js app with Twilio API routes, UI, and deployment config." },
  { command: "/build-python-app", description: "Generate a complete FastAPI or Flask Twilio backend with all endpoints and middleware." },
  { command: "/build-react-voip", description: "Build a browser-based VoIP client with Twilio Voice JS SDK — call, mute, DTMF, status." },
  { command: "/build-call-center", description: "Full call center system: IVR, queue, agent routing, recording, dashboard." },
  { command: "/build-sms-platform", description: "Complete SMS platform: send, receive, opt-out, drip campaigns, analytics." },
  { command: "/build-ai-voice-agent", description: "AI-powered voice agent using Twilio ConversationRelay + LLM (Claude/OpenAI)." },
  { command: "/build-whatsapp-bot", description: "Production WhatsApp bot: templates, 24h window, media, interactive messages." },
  { command: "/build-ivr-menu", description: "Multi-level IVR phone menu with DTMF/speech input and call routing." },
  { command: "/build-2fa-system", description: "Two-factor authentication system with Twilio Verify (SMS, TOTP, WhatsApp)." },
  { command: "/build-appointment-reminder", description: "Automated appointment reminder system: SMS + voice + cancellation flow." },
  { command: "/build-lead-nurture", description: "Lead nurturing pipeline: SMS drip, voice callbacks, CRM webhooks." },
  { command: "/build-conference-bridge", description: "Conference call bridge: PIN entry, recording, mute/kick controls, moderator." },
  { command: "/build-click-to-call", description: "Click-to-call widget: embed on any website, connects visitor to agent instantly." },
  { command: "/build-broadcast-system", description: "Mass broadcast system: send SMS/voice to thousands with opt-out compliance." },
  { command: "/build-voicemail-system", description: "Voicemail system: record, transcribe, email notification, playback portal." },
  { command: "/build-phone-tree", description: "Dynamic phone tree: department routing, business hours, holiday schedules." },
  { command: "/build-chatbot-handoff", description: "Chatbot with seamless handoff to live agent via Twilio Conversations." },
  { command: "/build-monitoring-alerts", description: "Usage monitoring system: trigger alerts, suspend numbers at cost thresholds." },

  // ─── INTEGRATIONS ───────────────────────────────────────────────────────────
  { command: "/integrate-gohighlevel", description: "Wire Twilio into GoHighLevel: inbound/outbound calls, SMS, webhooks." },
  { command: "/integrate-salesforce", description: "Salesforce + Twilio: CTI adapter, call logging, SMS from CRM, case creation." },
  { command: "/integrate-hubspot", description: "HubSpot CRM + Twilio: click-to-call, SMS, deal notifications, contact sync." },
  { command: "/integrate-openai", description: "OpenAI GPT + Twilio Voice: real-time AI voice agent with ConversationRelay." },
  { command: "/integrate-anthropic", description: "Claude + Twilio Voice: AI voice agent with streaming, tool use, memory." },
  { command: "/integrate-stripe", description: "Stripe + Twilio: payment confirmations via SMS, voice payment capture with <Pay>." },
  { command: "/integrate-zapier", description: "Zapier + Twilio: trigger SMS/calls from any app, parse inbound to Zap." },
  { command: "/integrate-n8n", description: "n8n workflow automation with Twilio nodes: SMS, calls, webhooks." },
  { command: "/integrate-make", description: "Make (Integromat) + Twilio: multi-step scenarios with SMS/voice triggers." },
  { command: "/integrate-airtable", description: "Airtable + Twilio: record-based SMS/call triggers, inbound data capture." },
  { command: "/integrate-notion", description: "Notion + Twilio: SMS to create pages, call summaries logged to database." },
  { command: "/integrate-slack", description: "Slack + Twilio: SMS/call alerts in channels, reply from Slack via SMS." },
  { command: "/integrate-shopify", description: "Shopify + Twilio: order SMS, shipping updates, abandoned cart recovery." },
  { command: "/integrate-wordpress", description: "WordPress plugin pattern: Twilio SMS contact form, WooCommerce order alerts." },
  { command: "/integrate-bubble", description: "Bubble.io + Twilio API Connector: SMS, verify, voice from no-code app." },
  { command: "/integrate-flutterflow", description: "FlutterFlow + Twilio: API calls, SMS auth, click-to-call mobile." },
  { command: "/integrate-supabase", description: "Supabase Edge Functions + Twilio: DB-triggered SMS, realtime webhooks." },
  { command: "/integrate-firebase", description: "Firebase Cloud Functions + Twilio: Firestore triggers, auth SMS, FCM+Twilio." },

  // ─── TWILIO PRODUCT SLASH COMMANDS ──────────────────────────────────────────
  { command: "/twilio-voice-ivr", description: "Create an Interactive Voice Response (IVR) flow using TwiML." },
  { command: "/twilio-sms-2way", description: "Build a 2-way SMS conversation application." },
  { command: "/twilio-whatsapp-bot", description: "Design a WhatsApp chatbot integration." },
  { command: "/twilio-flex-plugin", description: "Generate a custom Twilio Flex plugin structure." },
  { command: "/twilio-verify-otp", description: "Implement OTP verification using Twilio Verify." },
  { command: "/twilio-video-room", description: "Setup a programmable Video room." },
  { command: "/twilio-taskrouter", description: "Configure TaskRouter workflows and queues." },
  { command: "/twilio-studio-flow", description: "Design a Studio Flow JSON configuration." },
  { command: "/twilio-functions", description: "Create serverless Twilio Functions." },
  { command: "/twilio-sync", description: "Implement Twilio Sync for state management." },
  { command: "/twilio-conversations", description: "Setup a multi-channel Conversations API client." },
  { command: "/twilio-lookup", description: "Use Lookup API for phone number formatting and intelligence." },
  { command: "/twilio-event-streams", description: "Subscribe and process Event Streams." },
  { command: "/twilio-segment", description: "Integrate Segment for customer data tracking." },
  { command: "/twilio-sendgrid", description: "Configure SendGrid email delivery API." },
  { command: "/twilio-proxy", description: "Mask phone numbers using Twilio Proxy." },
  { command: "/twilio-sip-trunking", description: "Configure Elastic SIP Trunking settings." },
  { command: "/twilio-pay", description: "Implement secure payment processing via <Pay> TwiML." },
  { command: "/twilio-client", description: "Build a web-based VoIP client using Twilio Voice JS SDK." },
  { command: "/twilio-intelligence", description: "Use Voice Intelligence to analyze call transcripts." },
  { command: "/twilio-conversationrelay", description: "Build AI voice agent with ConversationRelay WebSocket." },
  { command: "/twilio-rcs", description: "Send rich RCS business messages with cards, carousels, actions." },
  { command: "/twilio-10dlc", description: "Register 10DLC brand and campaign for A2P SMS compliance." },

  // ─── CODE PATTERNS ──────────────────────────────────────────────────────────
  { command: "/code-webhook-handler", description: "Production webhook handler: signature validation, logging, retry-safe." },
  { command: "/code-token-server", description: "AccessToken server endpoint: mint, rotate, refresh for Voice/Chat/Sync." },
  { command: "/code-twiml-router", description: "TwiML router: dynamic menu, language selection, caller ID lookup." },
  { command: "/code-status-callback", description: "Status callback handler: log every call/message state transition." },
  { command: "/code-recording-handler", description: "Recording lifecycle handler: download, store S3, transcribe, notify." },
  { command: "/code-sms-parser", description: "Inbound SMS parser: keyword routing, NLP intent, auto-reply logic." },
  { command: "/code-rate-limiter", description: "Rate limiting for Twilio webhooks: Redis-backed, per-number throttle." },
  { command: "/code-error-handler", description: "Production error handler: Twilio error codes, retry logic, alerting." },
  { command: "/code-number-provisioner", description: "Auto-provision phone numbers: search, buy, configure, assign." },
  { command: "/code-multi-tenant", description: "Multi-tenant Twilio architecture: per-customer credentials, isolation." },
];
