export const SLASH_COMMANDS = [
  { command: "/twilio-voice-ivr", description: "Create an Interactive Voice Response (IVR) flow using TwiML." },
  { command: "/twilio-sms-2way", description: "Build a 2-way SMS conversation application." },
  { command: "/twilio-whatsapp-bot", description: "Design a WhatsApp chatbot integration." },
  { command: "/twilio-flex-plugin", description: "Generate a custom Twilio Flex plugin structure." },
  { command: "/twilio-verify-otp", description: "Implement OTP verification using Twilio Verify." },
  { command: "/twilio-video-room", description: "Setup a programmable Video room." },
  { command: "/twilio-taskrouter", description: "Configure TaskRouter workflows and queues." },
  { command: "/twilio-studio-flow", description: "Design a Studio Flow JSON configuration." },
  { command: "/twilio-functions", description: "Create serverless Twilio Functions." },
  { command: "/twilio-sync", description: "Implement Twilio Sync for state management." },
  { command: "/twilio-conversations", description: "Setup a multi-channel Conversations API client." },
  { command: "/twilio-lookup", description: "Use Lookup API for phone number formatting and intelligence." },
  { command: "/twilio-autopilot", description: "Configure Autopilot conversational AI tasks." },
  { command: "/twilio-event-streams", description: "Subscribe and process Event Streams." },
  { command: "/twilio-segment", description: "Integrate Segment for customer data tracking." },
  { command: "/twilio-sendgrid", description: "Configure SendGrid email delivery API." },
  { command: "/twilio-proxy", description: "Mask phone numbers using Twilio Proxy." },
  { command: "/twilio-sip-trunking", description: "Configure Elastic SIP Trunking settings." },
  { command: "/twilio-wireless", description: "Manage IoT SIMs with Twilio Programmable Wireless." },
  { command: "/twilio-pay", description: "Implement secure payment processing via <Pay> TwiML." },
  { command: "/twilio-client", description: "Build a web-based VoIP client using Twilio Client JS." },
  { command: "/twilio-notify", description: "Send cross-channel notifications with Twilio Notify." },
  { command: "/twilio-chat", description: "Implement in-app chat using Programmable Chat." },
  { command: "/twilio-super-sim", description: "Configure Super SIM for global IoT connectivity." },
  { command: "/twilio-frontline", description: "Setup integration for Twilio Frontline." },
  { command: "/twilio-intelligence", description: "Use Voice Intelligence to analyze call transcripts." }
];
